server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DB_USERNAME:postgres.tseehmabwupmvfmszdpx}
    password: ${DB_PASSWORD:F9FzzBkrrPqMSyXI}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

  upload-dir: ${UPLOAD_DIR:uploads}

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:C:\Secrets\skillshare-1ce35-firebase-adminsdk-fbsvc-7346916d8c.json}